# Generated by Django 2.2 on 2019-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('hostname', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cpu_number', models.IntegerField()),
                ('mem_total', models.IntegerField()),
            ],
        ),
    ]
