# Generated by Django 2.2 on 2019-05-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0004_auto_20190510_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=25)),
                ('group_use', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=25)),
                ('instance_id', models.CharField(max_length=25)),
                ('port', models.IntegerField()),
                ('high_availability', models.CharField(max_length=25)),
            ],
        ),
    ]
