# Generated by Django 2.2 on 2019-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0005_databasegroup_databaseinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseinstance',
            name='group_name',
        ),
        migrations.AddField(
            model_name='databaseinstance',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
