# Generated by Django 2.2 on 2019-05-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0006_auto_20190511_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseInstance',
        ),
    ]
