# Generated by Django 2.2 on 2019-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0007_delete_databaseinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('instance_id', models.CharField(max_length=25)),
                ('port', models.IntegerField()),
                ('high_availability', models.CharField(max_length=25)),
            ],
        ),
    ]
