# Generated by Django 2.2 on 2019-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0008_databaseinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasegroup',
            name='group_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='databasegroup',
            name='instance_number',
            field=models.IntegerField(default=0),
        ),
    ]
