# Generated by Django 2.2 on 2019-05-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0009_auto_20190512_0621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseInstance',
        ),
    ]
