# Generated by Django 2.2 on 2019-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0010_delete_databaseinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_id', models.IntegerField()),
                ('mysql_version', models.CharField(max_length=50)),
                ('group_id', models.IntegerField()),
                ('instance_id', models.CharField(max_length=25)),
                ('instance_alias', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mysql_path', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('high_availability', models.CharField(max_length=25)),
            ],
        ),
    ]
