# Generated by Django 2.2 on 2019-05-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0011_databaseinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinstance',
            name='status',
            field=models.CharField(default='运行', max_length=25),
            preserve_default=False,
        ),
    ]
