# Generated by Django 2.2 on 2019-05-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0012_databaseinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='rman_path',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
