# Generated by Django 2.2 on 2019-05-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0014_databaseinstance_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_date', models.DateTimeField()),
                ('ins_id', models.CharField(max_length=25)),
                ('backup_folder_name', models.CharField(max_length=150)),
                ('backup_name', models.CharField(max_length=150)),
                ('gtid', models.CharField(max_length=150, null=True)),
                ('backup_file_size', models.CharField(max_length=150, null=True)),
                ('backup_status', models.CharField(max_length=150)),
            ],
        ),
    ]
