# Generated by Django 2.2 on 2019-05-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0015_databasebackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ins_id', models.CharField(max_length=25)),
                ('mysql_user', models.CharField(max_length=50)),
                ('mysql_password', models.CharField(max_length=50)),
                ('mysql_db', models.CharField(max_length=50)),
                ('sql_statement', models.TextField()),
                ('audit_status', models.CharField(max_length=50)),
                ('online_status', models.CharField(max_length=50)),
                ('apply_user', models.CharField(max_length=50)),
                ('audit_user', models.CharField(max_length=50, null=True)),
                ('apply_date', models.DateTimeField()),
                ('audit_date', models.DateTimeField(null=True)),
                ('online_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
