# Generated by Django 2.2 on 2019-05-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0016_sqlaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlaudit',
            name='reasons_for_failure',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
