# Generated by Django 2.2 on 2019-05-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0018_monitordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySQLMonitorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('read', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Slow_queries', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Threads_created', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TPS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ibp_read_requests', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Connections', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Questions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ibp_not_read_requests', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QPS', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
