# Generated by Django 2.2 on 2019-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDBMP', '0019_mysqlmonitordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqlmonitordata',
            name='write',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
